builds:
  - id: operator
    binary: decco-operator
    main: ./cmd/operator
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
  - id: springboard
    binary: springboard
    main: ./cmd/springboard
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
archives:
  # Use values used by `uname` (OS) and `uname -m` (architecture).
  - id: default
    name_template: >-
      {{- .decco }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    builds:
      - operator
      - springboard
    files:
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT-{{.Commit}}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  - dockerfile: ./support/operator/Dockerfile
    goos: linux
    goarch: amd64
    ids:
      - decco-operator
    image_templates:
      - "docker.io/platform9/decco-operator:latest"
      - "docker.io/platform9/decco-operator:{{ .Tag }}"
  # TODO(erwin) add springboard docker