apiVersion: kind.sigs.k8s.io/v1alpha3
kind: Cluster
nodes:
  - role: control-plane
    extraPortMappings:
      # Decco Ingress
      - containerPort: 30443
        hostPort: 30443
        protocol: tcp