apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --enable-leader-election
        - --disable-app-controller
        image: controller:latest
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 40Mi
          requests:
            cpu: 100m
            memory: 40Mi
        env:
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
#          - name: DNS_PROVIDER_NAME
#            value: aws-route53
#          - name: AWS_ACCESS_KEY_ID
#            valueFrom:
#              secretKeyRef:
#                name: decco-operator-secret
#                key: awsAccessKeyId
#          - name: AWS_SECRET_ACCESS_KEY
#            valueFrom:
#              secretKeyRef:
#                name: decco-operator-secret
#                key: awsSecretAccessKey
#          - name: SLACK_WEBHOOK_FOR_DNS_UPDATE_FAILURE
#            valueFrom:
#              secretKeyRef:
#                name: decco-operator-secret
#                key: slackWebhookForDnsUpdateFailure

      terminationGracePeriodSeconds: 10
