apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin # TODO(erwin) replace with "manager-role" if we want to narrow RBAC (needs to be regenerated too)
subjects:
- kind: ServiceAccount
  name: default
  namespace: system
