apiVersion: v1
kind: ConfigMap
metadata:
  name: k8sniff-configmap
  namespace: decco
data:
  k8sniff.json: |
    {
        "bind": {
            "host": "0.0.0.0",
            "port": 8443
        },
        "kubernetes": {}
    }
