apiVersion: v1
kind: Secret
metadata:
  name: decco-operator-secret
  namespace: decco
type: Opaque
data:
  awsAccessKeyId: {{ .Values.aws_access_key_id | b64enc }}
  awsSecretAccessKey: {{ .Values.aws_secret_access_key | b64enc }}
  slackWebhookForDnsUpdateFailure: "{{ .Values.slack_webhook_for_dns_update_failure }}"
