apiVersion: v1
data:
  tls.crt: {{ .Values.wildcard_tls_cert | b64enc }}
  tls.key: {{ .Values.wildcard_tls_key | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: http-wildcard-cert
  namespace: decco
type: Opaque
