apiVersion: v1
kind: Service
metadata:
  name: k8sniff-metrics
  namespace: decco
  labels:
    monitoring-group: decco
spec:
  ports:
    - port: 9091
      name: metrics
      targetPort: 9091
      protocol: TCP
  selector:
    role: k8sniff
