# This template is used to force the evaluation of vars that are required using the
# `required` function without needing to litter the kube templates themselves.
# It is a weird pattern but I can't find a better one.

# !!! This file must only contain comments. !!!

# {{ required "aws_access_key_id is required from values.yaml" .Values.aws_access_key_id }}
# {{ required "aws_secret_access_key is required from values.yaml" .Values.aws_secret_access_key }}

# {{ required "wildcard_tls_cert is required from values.yaml" .Values.wildcard_tls_cert }}
# {{ required "wildcard_tls_key is required from values.yaml" .Values.wildcard_tls_key }}

# {{ required "tcp_tls_ca is required from values.yaml" .Values.tcp_tls_ca }}
# {{ required "tcp_tls_cert is required from values.yaml" .Values.tcp_tls_cert }}
# {{ required "tcp_tls_key is required from values.yaml" .Values.tcp_tls_key }}
