apiVersion: v1
data:
  ca.pem: {{ .Values.tcp_tls_ca | b64enc }}
  tls.crt: {{ .Values.tcp_tls_cert | b64enc }}
  tls.key: {{ .Values.tcp_tls_key | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: tcp-cert
  namespace: decco
type: Opaque
