---
decco_operator_image_tag: platform9/decco-operator:1.0.1-104
k8sniff_replicas: 1
k8sniff_image_tag: platform9/k8sniff:1.0.0-114

nginx_ingress_image_tag: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.19.0
default_http_backend_image_tag: gcr.io/google_containers/defaultbackend:1.0

# The following are all required secret values, so you'll find no defaults here!

# aws_access_key_id_b64: ''
# aws_secret_access_key_b64: ''

# wildcard_tls_cert_b64: ''
# wildcard_tls_key_b64: ''

# tcp_tls_ca_b64: ''
# tcp_tls_cert_b64: ''
# tcp_tls_key_b64: ''


# This last value is a secret as well, but is actually optional.
slack_webhook_for_dns_update_failure: ''

...
